Game logic
sz16900/tic-tac-toe-ruby pull request #4
Opened 2020-03-05 22:05 UTC by sz16900

# **Milestone 3: Game logic**

## **Suggested branch name game_logic.**

- Add real logic for your game - get rid of all inline comments and mocked logic used in previous milestone.
- As main.rb file should be responsible for user interaction, this is the only(!) one place where puts/print and get.chomp can be used.
- Think how you can encapsulate diffrent parts of game logic in classes. Do not create one class for everything.
- Read about DRY rule and use it.
- Think about the diffrence between attr_readers/attr_writers and atrr_acessors. Use atrr_acessors only if you really need it.
- Remember about single responsibility rule. Always.
- Remember to cover edge cases: think what player could try to do to cheat the game and make sure that your program does not allow to perform invalid action.

## **Our Improvements**

- Added scoreboard.
- Added infinite game loop until prompted to end game.

2020-03-06 05:25 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @sz16900  and @fdezcaminero  :balloon: :lollipop: 

### First of all :clap: claps to you for having a descriptive Readme file at this point, and for the descriptive pull request :bowing_woman:  it will definitely be less to work on for the next milestone :medal_sports: :medal_sports: secondly, your project works, is playable and you've done a good work keeping your code dry.
 
### there is still some work :construction: :construction_worker_man: :construction_worker_man:  to do and I have made comments on your code with the changes that you need to make so please address them bellow :arrow_double_down: 

### Also address this

- [ ]  whenever the player decides to play again, Player O always starts the game regardless if he/she lost the previous match.

### That's it, team! :raised_hands: 

### Please :pray: do the changes :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-03-06 05:25 UTC, euqueme commented on lib/display.rb
> +  end
- [ ] All puts, prints and gets chomps should be in the main.rb file, all methods should return only objects (strings, integers, booleans, boards, games) 

For example: here you could store the board in a string and return the string and just call puts print_board(board) somewhere within your main.rb file

2020-03-06 05:25 UTC, euqueme commented on lib/display.rb
> +  end
- [x] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). this one is not only printing and requesting for input is also validating, move all the printing and request for input to the main.rb

2020-03-06 05:25 UTC, euqueme commented on lib/display.rb
> +  end
- [ ] All puts, prints and gets chomps should be in the main.rb file, all methods should return only objects (strings, integers, booleans, boards, games) so please modify your position_taken, player_wins and draw methods

2020-03-06 05:25 UTC, euqueme commented on lib/display.rb
> +  end
- [ ] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). score_board and play_again? are not only printing and/or requesting for input they are also validating, move all the printing and request for input to the main.rb

2020-03-06 05:25 UTC, euqueme commented on lib/game.rb
> +  end
- [ ] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). start and end_game_handler have many responsibilities

Tip: I think these methods could be avoided you only need a loop in your main.rb with most of the logic of these methods, let's work on it

2020-03-07 15:03 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @sz16900 and @fdezcaminero :handshake: :handshake: 

### Thank you for doing the changes I requested in the first review, :medal_sports: :medal_sports:  your project looks more organized, I can see you created a loop in your main file which is the ideal here :ok_hand: there is still some work to do:

## Implementation details

#### single responsibility rule for methods

- [ ] The methods you have within your main file (win_method, draw_method and end_game_handler) are still not following the single responsibility rule, you are printing and also retrieving values, move all the printing to the loop so your methods have one single responsibility.

## unexpected behavior:

- [ ] when a player wins, the game is asking the next player to make a move when it should display the winning message right away

![image](https://user-images.githubusercontent.com/52209067/76145672-4ab1b880-6051-11ea-8c82-54dcfe7b0de4.png)

- [ ] when a player wins with the last move the game is counting it as a draw instead of a win for the player

![image](https://user-images.githubusercontent.com/52209067/76145750-08d54200-6052-11ea-8cf6-dac998256575.png)

### That's it, team! :raised_hands: 

### Please :pray: do the changes :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-03-09 18:37 UTC, pelzolga123 approved these changes
Approved!

2020-03-09 18:38 UTC, pelzolga123 commented
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to development.
_Goodluck in your next project_ *Happy coding*

2020-03-09 19:06 UTC, merged